export const AssetIds = {
  images: {
    background: 'background',
    homeLogo: 'homeLogo',
    shopLogo: 'shopLogo',
    shopMan: 'shopMan',
    shopSpeechBubble: 'shopSpeechBubble',
    medalsSheet: 'medalsSheet',
    confettiLayer1: 'confettiLayer1',
    confettiLayer2: 'confettiLayer2',
    confettiLayer3: 'confettiLayer3',
    buttonPink: 'buttonPink',
    buttonGold: 'buttonGold',
    buttonCyan: 'buttonCyan',
    panelCyan: 'panelCyan',
    footerPurple: 'footerPurple',
    iconCoin: 'iconCoin',
    iconShop: 'iconShop',
    iconHeart: 'iconHeart',
    iconTrophy: 'iconTrophy',
    iconInfinity: 'iconInfinity',
    iconPlay: 'iconPlay',
    iconSettings: 'iconSettings',
    iconBack: 'iconBack',
    iconMusic: 'iconMusic',
    iconVolume: 'iconVolume',
    iconLock: 'iconLock',
    iconShare: 'iconShare',
    iconShield: 'iconShield',
  },
  judges: {
    blingbeakDefault: 'judge.blingbeak.default',
    blingbeakPartyhat: 'judge.blingbeak.partyhat',
    blingbeakMaverick: 'judge.blingbeak.maverick',
    headbandDefault: 'judge.disco.default',
    discoSkin: 'judge.disco.disco',
    galaxyBrain: 'judge.disco.galaxy_brain',
    coolmanDefault: 'judge.coolman.default',
    coolmanKing: 'judge.coolman.king',
    dolphin: 'judge.coolman.dolphin',
    djDefault: 'judge.dj.default',
    punk: 'judge.dj.punk',
    labCoat: 'judge.dj.lab_coat',
  },
  stagePortraits: {
    stage1: 'stage.1.portrait',
    stage2: 'stage.2.portrait',
    stage3: 'stage.3.portrait',
    stage4: 'stage.4.portrait',
    stage5: 'stage.5.portrait',
  },
  music: {
    blingbeak: 'music.blingbeak',
    disco: 'music.disco',
    coolman: 'music.coolman',
    dj: 'music.dj',
  },
  sfx: {
    cancelClick: 'cancelClick',
    click: 'click',
    coinCountTick: 'coinCountTick',
    coinRewardBurst: 'coinRewardBurst',
    combo10: 'combo10',
    combo25Plus: 'combo25Plus',
    countdownTick: 'countdownTick',
    gradeReveal: 'gradeReveal',
    hitGood: 'hitGood',
    hitMiss: 'hitMiss',
    hitOkay: 'hitOkay',
    judgeReactNegative: 'judgeReactNegative',
    judgeReactPositive: 'judgeReactPositive',
    medalPop: 'medalPop',
    milestone: 'milestone',
    purchaseSuccess: 'purchaseSuccess',
    runFailed: 'runFailed',
    scratch: 'scratch',
    stageClear: 'stageClear',
    targetSpawn: 'targetSpawn',
  },
}

export const JudgeImageUrls = {
  [AssetIds.judges.blingbeakDefault]: 'characters/BlingBeak.png',
  [AssetIds.judges.blingbeakPartyhat]: 'characters/Partyhat.png',
  [AssetIds.judges.blingbeakMaverick]: 'characters/Maverick.png',
  [AssetIds.judges.headbandDefault]: 'characters/Headband.png',
  [AssetIds.judges.discoSkin]: 'characters/Disco.png',
  [AssetIds.judges.galaxyBrain]: 'characters/Galaxy_Brain.png',
  [AssetIds.judges.coolmanDefault]: 'characters/CoolMan.png',
  [AssetIds.judges.coolmanKing]: 'characters/King.png',
  [AssetIds.judges.dolphin]: 'characters/Dolphin.png',
  [AssetIds.judges.djDefault]: 'characters/DJ.png',
  [AssetIds.judges.punk]: 'characters/Punk.png',
  [AssetIds.judges.labCoat]: 'characters/Lab_Coat.png',
}

export const StagePortraitUrls = {
  [AssetIds.stagePortraits.stage1]: 'characters/stage-sprites/ferret-default.png',
  [AssetIds.stagePortraits.stage2]: 'characters/stage-sprites/manatee-default.png',
  [AssetIds.stagePortraits.stage3]: 'characters/stage-sprites/lemur-default.png',
  [AssetIds.stagePortraits.stage4]: 'characters/stage-sprites/vulture-default.png',
  [AssetIds.stagePortraits.stage5]: 'characters/stage-sprites/vulture-alt2.png',
}
