export const AssetIds = {
  images: {
    background: "background",
    homeLogo: "homeLogo",
    shopLogo: "shopLogo",
    shopMan: "shopMan",
    shopSpeechBubble: "shopSpeechBubble",
    medalsSheet: "medalsSheet",
    confettiLayer1: "confettiLayer1",
    confettiLayer2: "confettiLayer2",
    confettiLayer3: "confettiLayer3",
    buttonPink: "buttonPink",
    buttonGold: "buttonGold",
    buttonCyan: "buttonCyan",
    panelCyan: "panelCyan",
    footerPurple: "footerPurple",
    iconCoin: "iconCoin",
    iconShop: "iconShop",
    iconHeart: "iconHeart",
    iconTrophy: "iconTrophy",
    iconInfinity: "iconInfinity",
    iconPlay: "iconPlay",
    iconSettings: "iconSettings",
    iconBack: "iconBack",
    iconMusic: "iconMusic",
    iconVolume: "iconVolume",
    iconLock: "iconLock",
    iconShare: "iconShare",
    iconShield: "iconShield",
  },
  judges: {
    blingbeakDefault: "judge.blingbeak.default",
    blingbeakPartyhat: "judge.blingbeak.partyhat",
    blingbeakMaverick: "judge.blingbeak.maverick",
    headbandDefault: "judge.disco.default",
    discoSkin: "judge.disco.disco",
    galaxyBrain: "judge.disco.galaxy_brain",
    coolmanDefault: "judge.coolman.default",
    coolmanKing: "judge.coolman.king",
    dolphin: "judge.coolman.dolphin",
    djDefault: "judge.dj.default",
    punk: "judge.dj.punk",
    labCoat: "judge.dj.lab_coat",
  },
  stagePortraits: {
    stage1: "stage.1.portrait",
    stage2: "stage.2.portrait",
    stage3: "stage.3.portrait",
    stage4: "stage.4.portrait",
    stage5: "stage.5.portrait",
  },
  music: {
    blingbeak: "music.blingbeak",
    disco: "music.disco",
    coolman: "music.coolman",
    dj: "music.dj",
  },
  sfx: {
    cancelClick: "cancelClick",
    click: "click",
    coinCountTick: "coinCountTick",
    coinRewardBurst: "coinRewardBurst",
    combo10: "combo10",
    combo25Plus: "combo25Plus",
    countdownTick: "countdownTick",
    gradeReveal: "gradeReveal",
    hitGood: "hitGood",
    hitMiss: "hitMiss",
    hitOkay: "hitOkay",
    judgeReactNegative: "judgeReactNegative",
    judgeReactPositive: "judgeReactPositive",
    medalPop: "medalPop",
    milestone: "milestone",
    purchaseSuccess: "purchaseSuccess",
    runFailed: "runFailed",
    scratch: "scratch",
    stageClear: "stageClear",
    targetSpawn: "targetSpawn",
  },
} as const;

// Replace `unknown` with MHS TextureAsset/SoundComponent reference types after copying into MHS.
export const ImageAssets: Record<string, unknown> = {
  background: new TextureAsset("@sprites/background.png"),
  homeLogo: new TextureAsset("@sprites/ui/home-logo.png"),
  shopLogo: new TextureAsset("@sprites/ui/shop-logo.png"),
  shopMan: new TextureAsset("@sprites/ui/shop-man.png"),
  shopSpeechBubble: new TextureAsset("@sprites/ui/shop-speech-bubble.png"),
  medalsSheet: new TextureAsset("@sprites/ui/medals-sheet.png"),
  confettiLayer1: new TextureAsset("@sprites/ui/confetti-layer-1.png"),
  confettiLayer2: new TextureAsset("@sprites/ui/confetti-layer-2.png"),
  confettiLayer3: new TextureAsset("@sprites/ui/confetti-layer-3.png"),
  buttonPink: new TextureAsset("@sprites/ui/button-pink-wide.png"),
  buttonGold: new TextureAsset("@sprites/ui/button-gold-wide.png"),
  buttonCyan: new TextureAsset("@sprites/ui/button-cyan-wide.png"),
  panelCyan: new TextureAsset("@sprites/ui/panel-cyan-large.png"),
  footerPurple: new TextureAsset("@sprites/ui/footer-purple.png"),
  iconCoin: new TextureAsset("@sprites/icons/coin.png"),
  iconShop: new TextureAsset("@sprites/icons/shop.png"),
  iconHeart: new TextureAsset("@sprites/icons/heart.png"),
  iconTrophy: new TextureAsset("@sprites/icons/trophy.png"),
  iconInfinity: new TextureAsset("@sprites/icons/infinity.png"),
  iconPlay: new TextureAsset("@sprites/icons/play.png"),
  iconSettings: new TextureAsset("@sprites/icons/settings.png"),
  iconBack: new TextureAsset("@sprites/icons/back.png"),
  iconMusic: new TextureAsset("@sprites/icons/music.png"),
  iconVolume: new TextureAsset("@sprites/icons/volume.png"),
  iconLock: new TextureAsset("@sprites/icons/lock.png"),
  iconShare: new TextureAsset("@sprites/icons/share.png"),
  iconShield: new TextureAsset("@sprites/icons/shield.png"),
  "judge.blingbeak.default": new TextureAsset("@sprites/characters/BlingBeak.png"),
  "judge.blingbeak.partyhat": new TextureAsset("@sprites/characters/Partyhat.png"),
  "judge.blingbeak.maverick": new TextureAsset("@sprites/characters/Maverick.png"),
  "judge.disco.default": new TextureAsset("@sprites/characters/Headband.png"),
  "judge.disco.disco": new TextureAsset("@sprites/characters/Disco.png"),
  "judge.disco.galaxy_brain": new TextureAsset("@sprites/characters/Galaxy_Brain.png"),
  "judge.coolman.default": new TextureAsset("@sprites/characters/CoolMan.png"),
  "judge.coolman.king": new TextureAsset("@sprites/characters/King.png"),
  "judge.coolman.dolphin": new TextureAsset("@sprites/characters/Dolphin.png"),
  "judge.dj.default": new TextureAsset("@sprites/characters/DJ.png"),
  "judge.dj.punk": new TextureAsset("@sprites/characters/Punk.png"),
  "judge.dj.lab_coat": new TextureAsset("@sprites/characters/Lab_Coat.png"),
  "stage.1.portrait": new TextureAsset("@sprites/characters/BlingBeak.png"),
  "stage.2.portrait": new TextureAsset("@sprites/characters/stage-sprites/ferret-default.png"),
  "stage.3.portrait": new TextureAsset("@sprites/characters/stage-sprites/manatee-default.png"),
  "stage.4.portrait": new TextureAsset("@sprites/characters/stage-sprites/lemur-default.png"),
  "stage.5.portrait": new TextureAsset("@sprites/characters/stage-sprites/vulture-alt2.png"),
};

export const SoundComponentNames = {
  cancelClick: "CancelClick",
  click: "Click",
  coinCountTick: "CoinCountTick",
  coinRewardBurst: "CoinRewardBurst",
  combo10: "Combo10",
  combo25Plus: "Combo25Plus",
  countdownTick: "CountdownTick",
  gradeReveal: "GradeReveal",
  hitGood: "HitGood",
  hitMiss: "HitMiss",
  hitOkay: "HitOkay",
  judgeReactNegative: "JudgeReactNegative",
  judgeReactPositive: "JudgeReactPositive",
  medalPop: "MedalPop",
  milestone: "Milestone",
  purchaseSuccess: "PurchaseSuccess",
  runFailed: "RunFailed",
  scratch: "Scratch",
  stageClear: "StageClear",
  targetSpawn: "TargetSpawn",
  "music.blingbeak": "MusicBlingbeak",
  "music.disco": "MusicDisco",
  "music.coolman": "MusicCoolman",
  "music.dj": "MusicDj",
} as const;
